#ifndef __FLEXON_DEFS__
#define __FLEXON_DEFS__

enum justifyTypes {
  JUSTIFY_FLEX_START = 1,
  JUSTIFY_FLEX_END,
  JUSTIFY_CENTER,
  JUSTIFY_SPACE_BETWEEN,
  JUSTIFY_SPACE_AROUND,
  JUSTIFY_SPACE_EVENLY,
  JUSTIFY_START,
  JUSTIFY_END
};

enum alignTypes {
  ALIGN_CENTER = 1,
  ALIGN_BASELINE,
  ALIGN_STRETCH,
  ALIGN_FLEX_START,
  ALIGN_FLEX_END,
};

enum positionTypes {
  POSITION_ABSOLUTE = 1,
  POSITION_RELATIVE,
};
#endif
